### ISSUE TITLE
"." files are not deleted via explorer on mounted share.

### ISSUE THREAD

**Issue by Andy2244** [namjaejeon/cifsd#188]
I just tried to delete my test portableapps folder and noticed that's not possible. I tried delete via explorer on my top-folder and some files/folders will remain. They are also still visible via sftp, so its not some caching issue on windows.

Seems "." files are not deleted, maybe related to the `hide dot files` option.

```
root@router:/mnt/sda/2# ls -RA
.:
PortableApps

./PortableApps:
.nomedia         FirefoxPortable

./PortableApps/FirefoxPortable:
Data

./PortableApps/FirefoxPortable/Data:
profile

./PortableApps/FirefoxPortable/Data/profile:
storage

./PortableApps/FirefoxPortable/Data/profile/storage:
permanent

./PortableApps/FirefoxPortable/Data/profile/storage/permanent:
chrome

./PortableApps/FirefoxPortable/Data/profile/storage/permanent/chrome:
.metadata     .metadata-v2

```

**Comment by namjaejeon** [comment]
Ah, Okay, got it. .file should have beeen set hidden file flags instead of skipping lookup in query dir.
I am on vacation now. So I can fix it on this friday! Do you want to revert "hide dot file" patch once ?

**Comment by Andy2244** [comment]
> I am on vacation now.

Enjoy your vacation, no need for reverts at this point.

**Comment by namjaejeon** [comment]
Hm.. The issue is not clear even though I have fixed dot file bug. There is another bug(lookup issue). Looking into more.

**Comment by namjaejeon** [comment]
FIXED! Could you please check problem is clear on your side also ?
Thanks!

**Comment by Andy2244** [comment]
yes, fixed for me as well thanks
