### ISSUE TITLE
mount.cifs works with 2.0 even though CONFIG_CIFS_INSECURE_SERVER is not set

### ISSUE THREAD

**Issue by neheb** [namjaejeon/cifsd#189]
mount.cifs -o vers=1.0 fails correctly with kcifsd: smb_handle_negotiate:484: Unsupported SMB protocol

mount.cifs -o vers=2.0 succeeds

the Kconfig entry for CIFS_INSECURE_SERVER implies this should not be possible.

**Comment by namjaejeon** [comment]
@sergey-senozhatsky Could you pleae check this issue ?

**Comment by sergey-senozhatsky** [comment]
We allow SMB2 in INSECURE_SERVER. Only SMB1 is getting disabled.

<pre>
 34 #ifdef CONFIG_CIFS_INSECURE_SERVER                                              
 35         {                                                                       
 36                 SMB1_PROT,                                                      
 37                 "\2NT LM 0.12",                                                 
 38                 "NT1",                                                          
 39                 SMB10_PROT_ID                                                   
 40         },                                                                      
 41 #endif                                                                          
</pre>

-ss

**Comment by sergey-senozhatsky** [comment]
As far as I remember:
  Windows client starts negotiation using SMB2, which we then upgrade to SMB2+.
  If we disable SMB2 then Windows client connection fails.

-ss

**Comment by namjaejeon** [comment]
> config CIFS_INSECURE_SERVER
>    bool "Support for insecure SMB1/CIFS and SMB2.0 protocols"

@sergey-senozhatsky  Shoud we change Kconfig to avoid misunderstanding ?

**Comment by sergey-senozhatsky** [comment]
Hmm... No, seems that windows client is fine with disabled smb2.0

<pre>
[ 4729.040944] kcifsd: cifsd_lookup_dialect_by_name:210: client requested dialect ^BSMB 2.002
[ 4729.040945] kcifsd: cifsd_lookup_dialect_by_name:210: client requested dialect ^BSMB 2.???
[ 4729.040946] kcifsd: cifsd_lookup_dialect_by_name:213: selected ^BSMB 2.??? dialect
[ 4729.040947] kcifsd: cifsd_smb_negotiate_common:496: conn->dialect 0x2ff
[ 4729.040948] kcifsd: cifsd_smb_negotiate_common:502: Downgrade to SMB1 negotiation
[ 4729.040950] kcifsd: init_smb2_neg_rsp:251: conn->dialect 0x2ff
[ 4729.040951] kcifsd: cifsd_smb_negotiate_common:518: Upgrade to SMB2 negotiation
[ 4729.040952] kcifsd: smb2_set_rsp_credits:541: credits: requested[2] granted[1] total_granted[1]
[ 4729.041757] kcifsd: cifsd_tcp_conn_handler_loop:202: RFC1002 header 104 bytes
[ 4729.041765] kcifsd: cifsd_verify_smb_message:153: got SMB2 command
[ 4729.041767] kcifsd: smb2_calc_size:286: SMB2 data length 4 offset 100
[ 4729.041769] kcifsd: smb2_calc_size:302: SMB2 len 104
[ 4729.041770] kcifsd: cifsd_lookup_dialect_by_id:236: client requested dialect 0x210
[ 4729.041772] kcifsd: cifsd_lookup_dialect_by_id:236: client requested dialect 0x202
[ 4729.041773] kcifsd: cifsd_lookup_dialect_by_id:236: client requested dialect 0x210
[ 4729.041775] kcifsd: cifsd_lookup_dialect_by_id:236: client requested dialect 0x202
[ 4729.041776] kcifsd: cifsd_lookup_dialect_by_id:236: client requested dialect 0x210
[ 4729.041778] kcifsd: cifsd_lookup_dialect_by_id:236: client requested dialect 0x202
[ 4729.041779] kcifsd: cifsd_lookup_dialect_by_id:236: client requested dialect 0x210
[ 4729.041781] kcifsd: cifsd_lookup_dialect_by_id:236: client requested dialect 0x202
[ 4729.041782] kcifsd: cifsd_lookup_dialect_by_id:236: client requested dialect 0x210
[ 4729.041784] kcifsd: cifsd_lookup_dialect_by_id:243: selected ^BSMB 2.1 dialect
[ 4729.041785] kcifsd: cifsd_smb_negotiate_common:496: conn->dialect 0x210
</pre>

We try to use 2.x (which we don't support) or 2.1. So maybe we can disable SMB2.0
as well.


-ss

**Comment by sergey-senozhatsky** [comment]
Sent a patch. Tested on Windows 7 and smbclient.

-ss

**Comment by namjaejeon** [comment]
Applied!
@sergey-senozhatsky Thanks for your work!
@neheb Thanks for your feedback!

**Comment by neheb** [comment]
That was fast. Closing.
