### ISSUE TITLE
move cifsd-team/cifsd to cifsd-team/cifsd-old and move namjaejeon/cifsd to cifsd-team/cifsd

### ISSUE THREAD

**Issue by Neustradamus** [namjaejeon/cifsd#236]
First, it is possible to move cifsd-team/cifsd to cifsd-team/cifsd-archives (or cifsd-team/cifsd-old)
and move namjaejeon/cifsd to cifsd-team/cifsd

It will be better, I do not understand the fork ;)

https://help.github.com/articles/about-repository-transfers/

**Comment by Neustradamus** [comment]
@namjaejeon, @cifsd-team, @sergey-senozhatsky: Any news?

**Comment by sergey-senozhatsky** [comment]
Hi @Neustradamus,
Sorry, we don't have any updates yet. This is a low priority task; we do have a nuber of much bigger things going on.

-ss

**Comment by Neustradamus** [comment]
@namjaejeon, @cifsd-team, @sergey-senozhatsky: 5 minutes less to do it by repository ;)

**Comment by Neustradamus** [comment]
@namjaejeon, @cifsd-team, @sergey-senozhatsky, @launius, @hclee: 5 minutes less to do it by repository ;)

**Comment by Neustradamus** [comment]
@namjaejeon, @cifsd-team, @sergey-senozhatsky, @launius, @hclee: 5 minutes less to do it by repository ;)

**Comment by Neustradamus** [comment]
namjaejeon: Why have you closed this ticket without solution?
