### ISSUE TITLE
got 30816 err on windows side

### ISSUE THREAD

**Issue by pdo2013** [namjaejeon/cifsd#296]
server : centos 7 ,kernel 5.4.2
client 1: windows 10 error
client 2: centos 7 ,everything is ok.

client side error message on windows 10 ：
event 30816
The server does not support any dialect that the client is trying to negotiate, such as the client has SMB2/SMB3 disabled and the server has SMB1 disabled.

**Comment by namjaejeon** [comment]
I merged related bug fix to the master now. Could you try to test again ?

**Comment by pdo2013** [comment]
good ,I can mount it now ! so appreciate!

**Comment by namjaejeon** [comment]
Sorry, I did recently make some bug.
Thanks for your report!
