### ISSUE TITLE
WARNING: "vfs_read" [path/file.ko] undefined!

### ISSUE THREAD

**Issue by swati135** [namjaejeon/cifsd#41]
can anyone help me with this issue? I am trying to insert the driver into one of the reference board using fedora 27 kernel version 4.14.7. The same process runs with kernel version 4.13. 

Thank you

**Comment by namjaejeon** [comment]
Hi,

Could I see your full build log ?

Thanks.

**Comment by namjaejeon** [comment]
Hi,
I am about to reproduce your issue on 4.14 kernel. vfs_read/write export symbol was removed in 4.14.
I will fix it right now. and will inform you soon.
Thanks.

**Comment by namjaejeon** [comment]
Hi,
I fixed vfs_read/write undefined issue on latest master branch.
you can update codes, and try again :)

Thanks for your report!
